---
- name: Linux user creation
  hosts: db
  tasks:
    - name: create a multiple users
      user:
        name: "{{ item }}"
        state: present
      loop:
        - "joe"
        - "ravi"
        - "rani"
        - "mike"
