---
- name: copy the file
  hosts: db
  tasks:
    - name: copy file
      copy:
        src: test_script.sh
        dest: /tmp/test_script.sh
        owner: root
        group: root
        backup: yes